version: '3'

services:
   app:
     build: ./Devops/php
     container_name: app
     volumes:
       - .:/var/www/html
    #  depends_on:
    #    - app-mysql
    #    - app-redis

  #  app-mysql:
  #    image: mysql:5.7.22
  #    command: --innodb-use-native-aio=0
  #    restart: always
  #    ports:
  #      - "3306:3306"
  #    volumes:
  #      - "./db-mysql/dbdata:/var/lib/mysql"
  #    environment:
  #      - MYSQL_DATABASE= app
  #      - MYSQL_ROOT_PASSWORD= root
  
  #  app-redis:
  #    image: redis:alpine
  #    expose:
  #      - 6379

   app-nginx:
     build: ./Devops/nginx
     restart: always
     ports:
       - "9090:80"
     volumes:
       - ".:/var/www/html"
     depends_on:
       - app
     environment:
       VIRTUAL_HOST: dktools.local
